### PR TITLE
more words and figures on animal-telemetry

### PR DESCRIPTION
**Pull request by jdpye**
Added the other part of the acoustic lesson and a couple figures.

### CODE REVIEW

**Comment by jdpye** [comment]
I should have mentioned, Matt, Steve, if you have more flesh to put on the Satellite Telemetry side, specifically anything national you want to highlight, you're very welcome to dive in there.

**Comment by MathewBiddle** [comment]
Thanks @jdpye. I'm working up a few edits/additions now. Expect changes in a little bit. For example, I'd like to include ATN in here under the satellite telemetry section.

**Comment by jdpye** [comment]
That'd be grand. I didn't have the link to your ATN stat workflow R workup handy but it is very relevant reference material.

**Comment by MathewBiddle** [comment]
Okay, I made a bunch of edits. Take a look and LMK what you think. 

For the example time bin table, we can make that a dropdown to reduce clutter on the webpage.

**Comment by jdpye** [comment]
I like it. If you want to make the collapsible version of that table that's great, but these are all welcome additions.

**Comment by MathewBiddle** [comment]
okay, I'll merge this then you can check it out on the website.

**Review by MathewBiddle — APPROVED** [review]

**Comment by MathewBiddle** [comment]
@jdpye have a look see:
https://ioos.github.io/bio_mobilization_workshop/acoustic-telemetry/index.html

**Pull request merged**
