### PR TITLE
+ overview figure with links in SVG

### PR DESCRIPTION
**Pull request by bbest**
Added the following overview figure to main page...

## Overview

Click on the ? to be taken the relevant section of this workshop from this overview figure highlighting various resources used for core processes:

overview_bio-mobilization-workshop

## Editing

The figure can be edited here and downloaded as SVG into `figs/` for updating:

* [overview_bio-mobilization-workshop - Google Drawings](https://docs.google.com/drawings/d/1bPDCt2EQhGTUCDC-AJsBuKtcfUscZe_u_G9GLWyGO6M/edit)

### CODE REVIEW

**Comment by 7yl4r** [comment]
I love a good diagram and I think this is a very good diagram.

**Comment by MathewBiddle** [comment]
@bbest This is awesome! 

Curious about the links though as I get redirect notices for each one I click on:
image


Any way around that nuance?

**Comment by MathewBiddle** [comment]
Also wondering if this would be good to put on the [about](https://ioos.github.io/bio_mobilization_workshop/about/) page instead?

Probably would be good to publish it on your branch @bbest so folks can poke around.

**Comment by MathewBiddle** [comment]
nevermind, I see it here: https://bbest.github.io/bio_mobilization_workshop/

**Comment by bbest** [comment]
Hi @7yl4r and @MathewBiddle, 

Thanks for reviewing so quickly. I hadn't noticed those redirects before. I think it could be sorted later with some replacement of the URLs encoded in the SVG, eg:

```
https://www.gbif.org
```

turns into:

```
  https://www.google.com/url?q=https://www.gbif.org/ipt&amp;sa=D&amp;source=editors&amp;ust=1647299709374542&amp;usg=AOvVaw2mq7l9xuTawwA9XUsjN4to
```

**Comment by bbest** [comment]
I updated the Google Drawing [overview_bio-mobilization-workshop](https://docs.google.com/drawings/d/1bPDCt2EQhGTUCDC-AJsBuKtcfUscZe_u_G9GLWyGO6M/edit) and committed fixes to this PR with the following:

1. Fixed links to bypass **Redirect Notice** by confirming link in the Google Drawing by clicking on the link icon, not Apply:
  Screen Shot 2022-03-15 at 10 14 49 AM
2. Fixed link to **OBIS**
3. Added **GBIF**
4. Added "- minimum text fields" to **Metadata**

These are based on comments above and by @albenson-usgs:

1. Concern: The EML one I think it might confuse people that they need to create EML themselves but they don't need to do that.
1. The OBIS link goes to GBIF. Also wonder if we should add GBIF like [Enrique's diagram](https://github.com/ioos/bio_mobilization_workshop/blob/gh-pages/fig/DwC_workflow.jpg)?

You can see it live directly here:
https://bbest.github.io/bio_mobilization_workshop/#overview

**Comment by MathewBiddle** [comment]
@bbest sorry it's taken so long to get back around to this. How does everyone feel if we move this graphic to the About page?
https://ioos.github.io/bio_mobilization_workshop/about/
https://github.com/ioos/bio_mobilization_workshop/edit/gh-pages/_extras/about.md

I'd like to get it merged and available for folks to have a nice visual representation of our efforts. I would just like to keep the home page as strictly workshop details (connection info, schedule, dates, etc.). Which might evolve as we determine a solution for creating separate pages for different iterations.

**Comment by 7yl4r** [comment]
This is a difficult call. The graphic is a good overview; the "about" page doesn't feel like the ideal place. But it is also too much detail for the index page.

I think this graphic serves best as reference sheet for people who have completed the workshop. With that in mind, I propose adding new "extras" page for this graphic titled something like "data pipeline reference graphic"? 

Alternatively we could put it at the top of extras/reference

**Comment by MathewBiddle** [comment]
@7yl4r so create another extras page? Not sure about that title...seems a bit long

**Comment by albenson-usgs** [comment]
Really love the graphic and definitely want to get it added somewhere. I got a thumbs up on it from two OBIS colleagues. After our call today I'm not sure the best place for it. Worried we might end up with a bunch of extras pages but I supposed we can always combine them for later workshops if needed. I'm in favor of it's own extras page and naming it "Overview" since that's what it was intended to be- an overview of the workshop material.

**Comment by MathewBiddle** [comment]
@albenson-usgs does the About page not function as an overview? https://ioos.github.io/bio_mobilization_workshop/about/

I guess I'm not seeing the difference between your proposed Overview page and the existing About page. I agree that we don't want too many Extra pages, maybe a simple rename will make it clearer?

**Comment by 7yl4r** [comment]
because I did a squash merge on this bbest:gh-pages and ioos:gh-pages diverged. 
@bbest : you will need to reset bbest:gh-pages to ioos:gh-pages before being able to cleanly PR again.

If your `origin` remote is the bbest repo and you have an `upstream` remote as the ioos repo:

```
git checkout origin/gh-pages
git reset --hard upstream/gh-pages
git push -f origin/gh-pages
```

Just be careful that `origin` is not the ioos repo or you will force push over the branch we want to keep (including history).

I think you could also:
* delete the bbest fork and re-fork
* delete the bbest:gh-pages branch and create a new bbest:gh-pages branch from ioos:gh-pages

Sorry for the trouble.
I am still experimenting with advanced git usage to find the ideal workflow.

**Comment by bbest** [comment]
Hi @7yl4r  and all, 

Glad you find the figure useful and were able to incorporate into the About page.

Thanks for the steps to sync. I tried the suggested commands, but hit a snag. No worries though. I simply deleted my fork since the figure is now merged into the upstream repo.

```
bbest@Benjamins-MacBook-Air bio_mobilization_workshop % git checkout origin/gh-pages
Note: switching to 'origin/gh-pages'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 039abfc Merge branch 'ioos:gh-pages' into gh-pages
bbest@Benjamins-MacBook-Air bio_mobilization_workshop % git reset --hard upstream/gh-pages
fatal: ambiguous argument 'upstream/gh-pages': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Pull request merged**
