### PR TITLE
update links and basisOfRecord vocabularies

### PR DESCRIPTION
**Pull request by ymgan**
Sorry @MathewBiddle I did not notice that there were two repositories, so here you go, the PR requested for #41

### CODE REVIEW

**Comment by MathewBiddle** [comment]
interesting. It looks like you merged in changes from another PR, made your changes, and submitted this. Let me see how we can disentangle this.

**Comment by ymgan** [comment]
Sorry, I am not great with PR 🙈 just trying to help

**Comment by 7yl4r** [comment]
I think what happened is that this PR forked off of another branch. The easiest solution is to create a new branch off of ioos:gh-pages latest, then cherry pick 339f91af840c446d45de27d3156fb49b72233557 over to your new branch and submit a new PR.

**Comment by albenson-usgs** [comment]
@ymgan if it would be easier to send me the changes via email I can review them and put them into the main branch. Whatever is easiest for you!

**Comment by ymgan** [comment]
I am sorry, I am really busy 🙈 can you please have a look if the changes in this commit https://github.com/ioos/bio_mobilization_workshop/pull/42/commits/339f91af840c446d45de27d3156fb49b72233557 works for you? These are the only changes from me.

I am not sure myself if the links that I replaced are the correct ones because the current links are outdated and redirected (so I could not see the original page). @MathewBiddle suggested me to submit a PR so that he knows what I was talking about. Hope that works for you, thanks a lot!

**Comment by MathewBiddle** [comment]
Cherry picked the schema page and submitted a new PR https://github.com/ioos/bio_mobilization_workshop/pull/43

Sorry this was so troublesome. I was hoping we could figure out a way to cherry pick your PR, that way you get credit for your contributions here. Luckily you have submitted a PR that has been successfully merged, previously, making you a contributor to this project.

Closing this PR now.

**Pull request closed without merging**
