### PR TITLE
Updating content for website

### PR DESCRIPTION
**Pull request by MathewBiddle**
Adding links and syntax update.

### CODE REVIEW

**Review by 7yl4r — DISMISSED** [review]
Is that the right link? Maybe the wrong one got copy-pasted?

**Comment by MathewBiddle** [comment]
Thanks @7yl4r wrong link.

**Comment by MathewBiddle** [comment]
@albenson-usgs, @7yl4r, and @timvdstap please take a look at my changes to your respective sections. 

I think the Validation/Publishing part still needs some work.

**Review by MathewBiddle — COMMENTED** [review]
fixed

**Comment by MathewBiddle** [comment]
standby on this review

**Comment by MathewBiddle** [comment]
Should be easier to review now. Sorry about that.

**Review by 7yl4r — APPROVED** [review]

**Comment by MathewBiddle** [comment]
@albenson-usgs @timvdstap any comments?

**Pull request merged**
